version: '3'
services:
  api:
    build:
      context: ./back
    container_name: back
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      
  front:
    build: ./front
    container_name: front
    ports:
      - "4200:4200"